FROM php:8.0.0-apache
ARG DEBIAN_FRONTEND=noninteractive

# Instalar las dependencias
RUN apt-get update \
    && apt-get install -y sendmail libpng-dev \
    && apt-get install -y libzip-dev \
    && apt-get install -y zlib1g-dev \
    && apt-get install -y libonig-dev \
    && apt-get install -y libhiredis-dev \
    && rm -rf /var/lib/apt/lists/*

# Instalar extensiones adicionales
RUN docker-php-ext-install mysqli \
    && docker-php-ext-install mbstring \
    && docker-php-ext-install zip \
    && docker-php-ext-install gd

RUN a2enmod rewrite
